# Generated by Django 5.2 on 2025-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_city_country_remove_customer_address_customer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
