# Generated by Django 5.2 on 2025-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
