# Generated by Django 5.2 on 2025-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
