# Generated by Django 5.2 on 2025-04-22 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ec_categories',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_title', models.CharField(max_length=255)),
                ('feature_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sales', models.IntegerField(blank=True, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('feature_image1', models.FileField(blank=True, null=True, upload_to='features/')),
                ('feature_image2', models.FileField(blank=True, null=True, upload_to='features/')),
                ('feature_image3', models.FileField(blank=True, null=True, upload_to='features/')),
                ('feature_image4', models.FileField(blank=True, null=True, upload_to='features/')),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.categories')),
            ],
            options={
                'db_table': 'ec_features',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_description', models.TextField(blank=True, null=True)),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='banner/')),
                ('feature_id', models.ForeignKey(blank=True, db_column='feature_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.features')),
            ],
            options={
                'db_table': 'ec_banner',
            },
        ),
    ]
