# Generated by Django 5.2 on 2025-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerauthtokens',
            name='expiry_time',
            field=models.DateTimeField(db_column='auth_expiry_time', null=True),
        ),
    ]
