# Generated by Django 5.2 on 2025-04-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_customerauthtokens_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerauthtokens',
            name='expiry_time',
        ),
    ]
