# Generated by Django 5.2 on 2025-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_customerauthtokens_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerauthtokens',
            name='expired_at',
        ),
    ]
