# Generated by Django 5.2 on 2025-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_remove_customerauthtokens_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerauthtokens',
            name='expired_at',
            field=models.DateTimeField(db_column='auth_expired_at', null=True),
        ),
    ]
