# Generated by Django 5.2 on 2025-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='ec_cart',
        ),
    ]
