# Generated by Django 5.2 on 2025-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_amount',
            new_name='delivery_fees',
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
