# Generated by Django 5.2 on 2025-04-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('request_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ec_logs',
            },
        ),
    ]
