# Generated by Django 5.2 on 2025-05-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('product_discount', models.IntegerField(blank=True, null=True)),
                ('product_available_quantity', models.IntegerField(blank=True, null=True)),
                ('product_total_sales', models.IntegerField(blank=True, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_arival_date', models.DateField(blank=True, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('product_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_specification', models.JSONField(blank=True, null=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.categories')),
            ],
            options={
                'db_table': 'ec_products',
            },
        ),
        migrations.CreateModel(
            name='ProductReviewModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_review', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'ec_product_review',
            },
        ),
        migrations.CreateModel(
            name='ProductRatingModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_rating', models.IntegerField(blank=True, null=True)),
                ('product_review', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'ec_product_rating',
            },
        ),
    ]
