# Generated by Django 5.2 on 2025-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
