# Generated by Django 5.2 on 2025-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productratingmodel_productreviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='additional_specification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_dimension',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
