# Generated by Django 5.2 on 2025-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_additional_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productratingmodel',
            name='product_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productratingmodel',
            name='product_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='product_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
