# Generated by Django 5.2 on 2025-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productratingmodel_product_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratingmodel',
            name='product_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
